language: node_js

node_js: node

cache:
  directories:
    - node_modules

script:
  - yarn test
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        script: yarn semantic-release
